name: Garnet CI BDN.benchmark
on:
  workflow_dispatch:
  
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true

permissions:
  actions: write
  deployments: write  #permission to deploy GitHub pages website
  contents: write  # permission to update benchmark contents in gh-pages branch

jobs:
  changes:
    name: Check for changes
    runs-on: ubuntu-latest # don't need matrix to test where the changes were made in code
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Apply filter
      uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          website:
            - 'website/**'
          bdnbenchmark:
            - '!((*.md)|(website/**))'
  
  # Job to build and run BDN.benchmark
  build-run-bdnbenchmark:
    name: BDNBenchmark
    needs: [changes]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        framework: [ 'net8.0' ]
        configuration: [ 'Release' ]
        test: [ 'Resp.RespParseStress', 'Resp.RespTsavoriteStress', 'Cluster.RespClusterMigrateBench', 'Cluster.RespClusterBench', 'Resp.RespLuaStress', 'Resp.RespLuaRunnerStress' ]   
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Install dependencies
        run: dotnet restore

      - name: Run BDN.benchmark Perf Test
        run: .\test\BDNPerfTests\run_bdnperftest.ps1 ${{ matrix.test }}
        shell: pwsh
        continue-on-error: true
   
      - name: Upload test results to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Results-${{ matrix.os }}-${{ matrix.framework }}-${{ matrix.configuration }}-${{ matrix.test }}
          path: |
             ./test/BDNPerfTests/results
        if: ${{ always() }}

      - name: Upload Error Log to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ErrorLog-${{ matrix.os }}-${{ matrix.framework }}-${{ matrix.configuration }}-${{ matrix.test }}
          path: |
            ./test/BDNPerfTests/errorlog
        if: ${{ always() }}

      # Download previous benchmark result from cache (if exists)
      - name: Download previous benchmark data
        uses: actions/cache@v4
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark
      
      # Run `github-action-benchmark` action
      - name: Store benchmark result for charts
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: BDNBenchmark - ${{matrix.test}} (os ${{matrix.os}}, framework ${{matrix.framework}}, configuration ${{matrix.configuration}})
          tool: 'benchmarkdotnet'
          output-file-path: ./test/BDNPerfTests/BenchmarkDotNet.Artifacts/results/BDN.benchmark.${{ matrix.test }}-report-full-compressed.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          summary-always: true
          auto-push: true

      # Run `github-action-benchmark` action
      - name: Store benchmark result for commit comment
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: 'benchmarkdotnet'
          output-file-path: ./test/BDNPerfTests/BenchmarkDotNet.Artifacts/results/BDN.benchmark.${{ matrix.test }}-report-full-compressed.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          alert-threshold: '115%' 
          external-data-json-path: ./cache/benchmark-data.json
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@darrenge'
          summary-always: false
          auto-push: false  # needs to be false if using external-data-json-path
