name: CI - testing publish

on:
  workflow_dispatch:

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x' # Specify the .NET version you need

    - name: Build Garnet projects
      run: dotnet build '**/Garnet*.csproj' -c Release

    - name: Publish the GarnetServer binaries
      run: |
        pwsh ./.azure/pipelines/createbinaries.ps1 1
      shell: pwsh

