name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: dotnet build
      run: dotnet build '**/Garnet*.csproj' -c Release

    - name: Publish the GarnetServer binaries
      run: |
        pwsh ./.azure/pipelines/createbinaries.ps1 1
      shell: pwsh

    - name: Copy Zipped Files to Artifacts dir
      run: |
        mkdir -p ${{ github.workspace }}/artifacts
        cp -r ${{ github.workspace }}/main/GarnetServer/bin/Release/net8.0/publish/output/* ${{ github.workspace }}/artifacts/

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: drop
        path: ${{ github.workspace }}/artifacts